[Unit]
After=pipewire.socket

[Service]
ExecStartPre=/bin/bash -c 'timeout 10 bash -c "until [ -S \"$XDG_RUNTIME_DIR/pipewire-0\" ]; do sleep 0.2; done"'
RestartSec=1
StartLimitBurst=10
StartLimitIntervalSec=60
